- src/components/Checklist.vue
修复checklist的change事件会在demo中调用两次的问题。与之前XButton调用两次点击事件同理。
> fix twice change event

- src/components/number/index.vue
修复前bug表现为，当number组件的min或max属性设置为0时，无法达到预期结果。
会出现实际值小于最小值或者大于最大值的情况。
> 修正Number组件最大或最小值设置为0时无效的BUG

- src/components/x-textarea/index.vue
所以我们可以直接字面传入`max="20"`
http://vuejs.org/guide/components.html#Literal-vs-Dynamic
不知道是否有意义...
> add type cast for x-textarea

- src/components/popup-picker/index.vue
.vux-popup-picker-value 100%宽度删除
> 100%宽度导致后面的箭头看不见

- src/components/scroller/index.vue
支持重新挂载pullup插件。
使用场景是：
当页面只有一页的数据时，会`broadcast` `pullup:done` 将插件卸载。
当下拉刷新后，有数据新增，且页数超过了1页，那么希望重新挂载上拉刷新组件
> Scroller: support recovery pullup plugin

- src/components/datetime/datetimepicker.js
- src/components/datetime/index.vue
1. 把scroller-content的z-index设为-1可以正确显示background-image的渐变效果（Safari的锅）
2. 在隐藏的时候需要把-webkit-transform也remove了。不然在安卓的微信浏览器内会没有动画
> bug-fix：timepicker Safari下初始化窗口后渐变无效 微信浏览器内显示隐藏动画错误

- src/components/search/index.vue
因.weui_select有设置z-index为1，导致.vux-search-fixed的z轴反而低于.weui_select,会导致不能保证遮罩完全。z-index取5是参照.vux-search-mask,非必须，>=1皆可。
> add z-index in search of components

- src/components/x-img/index.vue
- src/demos/XImg.vue
Related #151
* 使用emit代替disptch
* 根据事件命名规范，修改了事件命名
* 更新了相应的Demo
@airyland Pls take a look, If it is ok, wil be merged.
> XImg: used emit instead of dispatch, and fixed event naming

- src/components/rater/index.vue
Statistically in more than a half situations, rater components are used as merely an presenting method. So there's no need of the value property of rater components to be set as two-way binding. Further more, if the value passed to a rater components from its parent components is a computed value or a value using filter, which might happen in some cliche system, `Vue` will throw out a warn error as follows:
`vconsole.min.js:6 [Vue warn]: Cannot bind two-way prop with non-settable parent path: parseInt(store.rate) (found in component: <rater>)`
Though this error will be hidden in production version of `Vue`, I think it should be issued in the component source level.
> Update rater components

- src/components/selector/index.vue
无因有无title而频繁切换场景，所以v-if优于v-show，减少编译量/时间
> Selector: replace v-show with v-if

- src/components/rater/index.vue
The line height of a rater a element should be adjusted as a function of its height and font size, not fixed as 25px. Otherwise if people use a different font size, vertical position of the rater character may be affected and incur some unexpected behavior.
> Remove static line height of rater

- src/components/toast/index.vue
测试在 iOS 下 微信内核浏览器，Safari浏览器，Toast 组件设置文本模式 Toast 提示框有最小高度值的问题，
具体可看官网 Demo https://vux.li/?x-page=github_readme#!/component/toast  （请用手机浏览 文字提示）
> 修复 Toast 文本模式下 最小高度问题

- src/components/popup/index.vue
- src/components/popup/popup.js
- src/demos/Popup.vue
#334 多层popup问题修正
#205 允许点击遮罩时不关闭popup, 由popup内部自行提供关闭按钮或者实现逻辑。在一些需要强制用户做操作的场景时很有用，也用于防止用户误点击触发了关闭导致未保存的数据丢失。
> Popup: Fixed multi popup and mask click disable

- src/components/checklist/index.vue
checklist的title为空时,不显示<div class="weui_cells_title">{{title}}</div>
因为weui_cells_title样式中的margin会让该div显示在页面上.
> title为空时隐藏div

- src/components/search/index.vue
组件：Search
- 更改：添加required配置属性
- 原因：填写之后若清空，则无法提交表单，无法进行无条件搜索
- 更改：提升类名`vux-search_show`优先级
- 原因：开发过程中引入源文件编译后发现，会有其他组件的`weui_cells`覆盖上述类样式
BTW：
- 周末发现search组件在配置`autoFixed: false`时，`取消按钮`会有交互问题。但是我用了其他的方式来修复，今天想提交发现已经修复了，而且顺便解决了`不吸顶时也显示取消按钮`的问题，赞一个~
- 以下是我当时的方案：
```html
...
<input type="hidden" id="hidden"/>
<label for="hidden">
<a href="javascript:" class="weui_search_cancel" id="search_cancel" @click="cancel">{{cancelText}}</a>
</label>
...
```
```js
// 解决autoFixed配置为true时无法focus问题
methods: {
...
touch () {
this.isCancel = false
->  // if (this.autoFixed) {
this.isFixed = true
->  // }
},
...
},
...
watch: {
isFixed (val) {
if (val === true) {
this.setFocus()
this.isFocus = true
->    this.autoFixed && this.$el.classList.add('vux-search-fixed')
} else { …
```
> Search: Add prop required & update class

- src/components/x-header/index.vue
修复x-header返回按钮点击区域过小的问题
Before:
after:
> fix x-header back click area

- src/components/inline-calendar/index.vue
日期单元格的data-date非当月的日期会计算成当月，例如当月是2016-08，日历7月份
那最后几天的data-date字段会显示为2016-08-xx，会造成replaceText时同一个月出现两个today。
> 修复inline calendar组件data-date字段计算错误的问题

- src/components/x-textarea/index.vue
```html
<x-textarea :value="textValue" :max="100"></x-textarea>
```
如上情况下，当 textValue 为 null 时，计算总字数时会报错，因为出现 null.length。虽然可以使用过滤器或者其它手段在自身业务中解决这一问题，但我觉得组件内部解决会方便更多人。
> x-textarea总字数计算中考虑文本框当前值为空或未定义情况

- src/mixins/multi-items.js
使用 tab 组件和 tab-item 动态生成子导航
```
<tab>
<tab-item>
<tab-item>
<tab-item>
</tab>
<tabbar>
<tabbar-item> // tabbar-item 1
<tabbar-item>
</tabbar>
```
```
<tab>
<tab-item>
<tab-item>
</tab>
<tabbar>
<tabbar-item>
<tabbar-item> // tabbar-item 2
</tabbar>
```
当从 tabbar-item 1 切换至 tabbar-item 2时，tab 中 tab-item 减少了 一项，此时 oldVal = 2, this.$children.length 为 2, 导致报错
**Uncaught TypeError: Cannot set property 'selected' of undefined**
> fix: 使用tab, 且tab-item为动态生成时切换菜单报错

- src/components/actionsheet/index.vue
Fix warning:
```
[Vue warn]: Invalid default value for prop "menus": Props with type Object/Array must use a factory function to return the default value. (found in component: <actionsheet>)
```
Discussion: https://github.com/vuejs/vue/issues/1032
> Fix actionsheet invalid default value warning
