- src/components/Circle/index.vue
> [bugfix] Fix wrong end of element tag

- package.json
- src/index.html
- src/main.js
* Add fastclick NPM module, invoke fastclick in main.js
* Remove fastclik scripts from index.html, also remove redundant tags
> Better way of importing fastclick

- src/components/clocker/index.vue
Remove the clocker element and the ticker, set clocker to null dons't delete the ticker
> [Bugfix] Remove Clocker Before  Destroy

- src/components/x-input/index.vue
- src/demos/Input.vue
* added solt for left area
* added div wrapper class when is invalid
* fix a bug for validate
> Input:  enhancement x-input

- src/components/toast/index.vue
- src/demos/Toast.vue
> Toast: add two type of icon

- src/components/x-number/index.vue
- src/demos/Number.vue
1. Changed the order of style and script
2. Rename change to on-change which followed the spec
> XNumber: Rename event

- src/components/checklist/index.vue
顺便问下这个参数是什么作用？没明白这个`fillMode` 开启之后的作用是啥
> Checklist: Fix invalid property check

- src/components/progress/index.vue
> Progress: rename event name cancel to on-cancel

- src/components/tab-item/index.vue
issue: 目前的情况是只能通过点击来选中tab，不能通过修改selected来选中。
fix:  通过修改selected来选中tab。
> tab-item: update index when the selected was changed

- src/main.js
enable vue-devtool in demo production environment
> enable devtool

- src/components/datetime/datetimepicker.css
- src/components/datetime/datetimepicker.js
增加datepicker显示隐藏时的过渡效果；
修复onShow回调会调用2次的问题。
> datetime: fix animation 

- src/components/x-input/index.vue
I'm not sure wheather it is correct or not.
> Add readonly property for x-input component.

- src/components/picker/scroller.js
The original height of component is 238 when hidden.
> update the method to get component height

- src/components/flexbox/index.vue
flex-col => vux-flex-col
flex-row => vux-flex-row
> flex-col & flex-row add vux-

- src/components/popup/popup.js
- src/demos/Popup.vue
> fixed multi popup

- src/components/popup-picker/index.vue
vux-header与组件x-header中类名冲突，更改后更安全/规范
> popup-picker:rewrite class vux-header

- package.json
- src/components/scroller/index.vue
- src/demos/PulldownPullup.vue
Resolve #233
@airyland @bammoo  Pls have a code review
> scroller: support reset pullup manually

- src/components/swiper/index.vue
- src/components/swiper/swiper.js
- src/demos/Swiper.vue
> Swiper: Reconstruction sliding mode and add loop attribute

- src/components/popup-picker/index.vue
> Popup-picker: Add on-change event on picker

- src/components/x-img/index.vue
> 添加 x-img blazy container 配置项

- src/components/x-textarea/index.vue
> x-textarea: fix word count bug

- src/components/datetime/datetimepicker.js
- src/components/datetime/index.vue
- src/demos/Datetime.vue
> picker的时间中间可以放个按钮，有时候需要特殊用途，比如清空值，因为有的地方做数据筛选的时候，可以显示全部（不带时间）

- src/components/swiper/index.vue
- src/components/swiper/swiper.js
- src/demos/Swiper.vue
修正#507 issue
通过重写go事件来修正内部go事件
> Swiper: Fixed loop issue. close #507 and fixed go event

- src/components/x-input/index.vue
> 首次验证最小值时没有显示错误提示,缩进格式做修改

- src/components/selector/index.vue
当传 options list 为 [{key: '', value: 'v'}] 时，会被处理为 [{key: {key: '', value: 'v'}, value: {key: '', value: 'v'}}]
> selector options 列表处理错误

- src/components/picker/index.vue
watch 在 ready 之前执行的情况下，由于 `this.scroller` 还未赋值，会报错`Cannot read property 'value' of undefined`
> fix: picker watch 报错

- src/components/swiper/index.vue
- src/components/swiper/swiper.js
- src/demos/Swiper.vue
> Swiper: support only two items

- src/components/x-input/index.vue
> x-input right slot 没有正确结束,Update index.vue

- src/main.js
> 首页动画固定为forward

- src/components/x-textarea/index.vue
> TextArea Add readonly prop

- src/mixins/multi-items.js
> Tab: fix bugs #677

- package.json
- src/components/countup/index.vue
- yarn.lock
Upgrade from ^1.6.1 to ^1.7.1
Resolve #692
> Countup: update countup depends

- src/components/tab/tab.vue
> 同时传进新旧两个index

- src/components/inline-calendar/util.js
> Calendar: fix bugs #685

- src/components/panel/index.vue
> Panel: fix bugs #686

- src/components/address/index.vue
- src/filters/value2name.js
In the demo, to get the address name one have to manually import value2name and use value and address array as two parameters. But I think a more elegant way is to provide a function inside the address components that can be called through component reference.
> Adding method to get address name

- src/components/checker/checker.vue
> 修复异步赋值v-model的bug

- src/components/selector/index.vue
- src/components/selector/metas.yml
修改selector组件value的数据类型为String, Number, Object
> 修改selector组件value的数据类型为String, Number, Object

- src/components/search/index.vue
- src/components/toast/index.vue
> Add on-touch event on search componment & fixed LoadingToast style problem

- src/components/confirm/index.vue
> 修复confirm组件不显示的bug

- src/components/calendar/index.vue
- src/components/inline-calendar/props.js
> Calendar: props fix

- src/components/datetime/format.js
> unicode转义字符的前缀应该是'\u'
